package domain

import (
	"strings"
	"time"

	"github.com/google/uuid"
)

// PaperIdentifiers holds all possible identifiers for an academic paper.
// Used by GenerateCanonicalID to create a stable, deduplicated identifier
// with a defined priority order: DOI > ArXiv > PubMed > SemanticScholar > OpenAlex > Scopus.
type PaperIdentifiers struct {
	// DOI is the Digital Object Identifier (e.g., "10.1038/s41586-021-03819-2").
	DOI string

	// ArXivID is the arXiv preprint identifier (e.g., "2103.14030").
	ArXivID string

	// PubMedID is the PubMed identifier (PMID) (e.g., "34108480").
	PubMedID string

	// PMCID is the PubMed Central identifier (e.g., "PMC8170772").
	PMCID string

	// SemanticScholarID is the Semantic Scholar corpus ID.
	SemanticScholarID string

	// OpenAlexID is the OpenAlex work identifier (e.g., "W2741809807").
	OpenAlexID string

	// ScopusID is the Scopus document identifier.
	ScopusID string
}

// GenerateCanonicalID generates a canonical identifier from paper identifiers.
// Priority order: DOI > ArXiv > PubMed > SemanticScholar > OpenAlex > Scopus
// Returns empty string if no identifiers are available.
func GenerateCanonicalID(ids PaperIdentifiers) string {
	// Check DOI first (highest priority)
	if doi := strings.TrimSpace(ids.DOI); doi != "" {
		// Normalize DOI to lowercase
		return "doi:" + strings.ToLower(doi)
	}

	// ArXiv ID
	if arxiv := strings.TrimSpace(ids.ArXivID); arxiv != "" {
		return "arxiv:" + arxiv
	}

	// PubMed ID
	if pubmed := strings.TrimSpace(ids.PubMedID); pubmed != "" {
		return "pubmed:" + pubmed
	}

	// Semantic Scholar ID
	if s2 := strings.TrimSpace(ids.SemanticScholarID); s2 != "" {
		return "s2:" + s2
	}

	// OpenAlex ID
	if openalex := strings.TrimSpace(ids.OpenAlexID); openalex != "" {
		return "openalex:" + openalex
	}

	// Scopus ID (lowest priority)
	if scopus := strings.TrimSpace(ids.ScopusID); scopus != "" {
		return "scopus:" + scopus
	}

	// No identifier available
	return ""
}

// Author represents a paper author with optional affiliation and ORCID.
type Author struct {
	Name        string `json:"name"`
	Affiliation string `json:"affiliation,omitempty"`
	ORCID       string `json:"orcid,omitempty"`
}

// String returns a formatted string representation of the author.
func (a Author) String() string {
	var sb strings.Builder
	sb.WriteString(a.Name)

	if a.Affiliation != "" {
		sb.WriteString(" (")
		sb.WriteString(a.Affiliation)
		sb.WriteString(")")
	}

	if a.ORCID != "" {
		sb.WriteString(" [")
		sb.WriteString(a.ORCID)
		sb.WriteString("]")
	}

	return sb.String()
}

// Paper represents an academic paper in the central repository.
// Papers are deduplicated by CanonicalID and may be enriched from multiple sources.
type Paper struct {
	// ID is the internal UUID primary key.
	ID uuid.UUID

	// CanonicalID is a stable, deduplicated identifier derived from the paper's external identifiers.
	// Generated by GenerateCanonicalID with format "prefix:value" (e.g., "doi:10.1234/example").
	CanonicalID string

	// Title is the paper's title.
	Title string

	// Abstract is the paper's abstract text.
	Abstract string

	// Authors is the ordered list of paper authors.
	Authors []Author

	// PublicationDate is the exact publication date, if known.
	PublicationDate *time.Time

	// PublicationYear is the publication year, used when the exact date is unavailable.
	PublicationYear int

	// Venue is the conference or venue where the paper was presented.
	Venue string

	// Journal is the journal name where the paper was published.
	Journal string

	// Volume is the journal volume number.
	Volume string

	// Issue is the journal issue number.
	Issue string

	// Pages is the page range within the journal issue (e.g., "123-145").
	Pages string

	// CitationCount is the number of citations this paper has received.
	CitationCount int

	// ReferenceCount is the number of references this paper cites.
	ReferenceCount int

	// PDFURL is the URL to the paper's PDF, used for ingestion.
	PDFURL string

	// OpenAccess indicates whether the paper is freely accessible.
	OpenAccess bool

	// KeywordsExtracted indicates whether the LLM has already extracted keywords from this paper.
	KeywordsExtracted bool

	// FileID is the file_service UUID for the downloaded PDF (populated after ingestion).
	FileID *uuid.UUID

	// IngestionRunID is the ingestion service run ID (populated after ingestion).
	IngestionRunID *string

	// RawMetadata holds the unprocessed metadata from the source API as a JSON object.
	RawMetadata map[string]interface{}

	// CreatedAt records when the paper was first added to the repository.
	CreatedAt time.Time

	// UpdatedAt records when the paper's metadata was last updated.
	UpdatedAt time.Time
}

// HasIdentifier returns true if the paper has at least one identifier.
func (p *Paper) HasIdentifier() bool {
	return p.CanonicalID != ""
}
